language:
  - cpp

before_install:
  - pip install --user cpp-coveralls
  - sudo apt-get install qtdeclarative5-dev qt5-default



script:
 "bundle exec rake test:$TEST_SUITE"
  - qmake -qt=qt5 -v
  - qmake -qt=qt5
  - make
  - ./tests/tests

after_success:
  - coveralls --root . -E ".*googletest.*" -E ".*moc_.*"

notifications:
email: false
