language:
  - cpp

before_install:
  - pip install --user cpp-coveralls
  - apt-get install qt5-dev-tools
script:
  - qmake
  - make
  - ./tests/tests

after_success:
  - coveralls --root . -E ".*external.*" -E ".*tests.*"

notifications:
  email: false
