language:
  - cpp

before_install:
  - pip install --user cpp-coveralls
  - sudo apt-get install qtdeclarative5-dev qt5-default

install:

travis_wait 30 mvn install

script:
  - qmake
  - make
  - ./tests/tests


after_success:

  - coveralls --root . -E ".*external.*" -E ".*tests.*"

notifications:
  email: false
