language:
  - cpp

before_install:
  - pip install --user cpp-coveralls
  - sudo apt-get update -qq
  - sudo apt-get install qt5-default  qttools5-dev-tools
  - sudo apt-get install qtbase5-dev
  - sudo apt-get install qtdeclarative5-dev
  - sudo apt-get install libqt5svg5-dev
  - sudo apt-get install qtmultimedia5-dev
  - sudo apt-get install -qq g++ qt4-qmake libqt4-dev qt5-qmake qtbase5-dev
  - sudo apt-get install qtquick1-5-dev qtscript5-dev

script:
  - qmake
  - make
  - ./tests/tests

after_success:
  - coveralls --root . -E ".*external.*" -E ".*tests.*"

notifications:
  email: false
