language:
  - cpp

before_install:
  - pip install --user cpp-coveralls
  - sudo apt-get install qttools5-dev-tools
  - sudo apt-get install qtbase5-dev
  - sudo apt-get install qtdeclarative5-dev qt5-default
  - sudo apt-get install libqt5svg5-dev
  - sudo apt-get install qtmultimedia5-dev
   script:
  - qmake -qt=qt5 -v
  - qmake -qt=qt5
  - make
  - ./tests/tests

after_success:
  - coveralls --root . -E ".*external.*" -E ".*tests.*"

notifications:
  email: false
