language:
  - cpp

before_install:
  - pip install --user cpp-coveralls
  - sudo apt-get install qt5-default qtbase5-dev qtdeclarative5-dev
  libqt5svg5-dev qtmultimedia5-dev
script:
  - qmake
  - make
  - ./tests/tests

after_success:
  - coveralls --root . -E ".*external.*" -E ".*tests.*"

notifications:
  email: false
